#!/bin/sh
sv check ../wayland-session || exit 1

WALLPAPER_DIR=$(eval echo "$(grep XDG_PICTURES_DIR ~/.config/user-dirs.dirs | cut -d'=' -f2 | tr -d '"')/Wallpaper")
WALLPAPER="$WALLPAPER_DIR/current"

exec chpst -e "$TURNSTILE_ENV_DIR" swaybg -i "$WALLPAPER"

