vim9script

g:mapleader = ' '

colorscheme novum
set background=dark

set number relativenumber
set ignorecase smartcase
set hidden

packadd comment
packadd cfilter
packadd matchit
packadd editorconfig
packadd termdebug
# external plugins are vendored, see pack/vendor/start

source ~/.config/vim/autocomplete.vim
source ~/.config/vim/lspconfig.vim
source ~/.config/vim/statusline.vim

nmap <silent> <leader>f <Cmd>Files<CR>
nmap <silent> <leader>g <Cmd>RG<CR>
nmap <silent> <leader>r <Cmd>MRU<CR>
nmap <silent> <Tab> <Cmd>bnext<CR>
nmap <silent> <S-Tab> <Cmd>bprevious<CR>

# yank/paste to clipboard
nnoremap <leader>y "+y
xnoremap <leader>y "+y
nnoremap <leader>Y "+Y
nnoremap <leader>p "+p
nnoremap <leader>P "+P
