#!/bin/sh
export TERMINAL=footclient \
	GTK_THEME=Adwaita:dark \
	QT_STYLE_OVERRIDE=Adwaita-Dark

export \
	XDG_SESSION_TYPE=wayland \
	GDK_BACKEND=wayland \
	QT_QPA_PLATFORM=wayland-egl \
	MOZ_ENABLE_WAYLAND=1 \
	CLUTTER_BACKEND=wayland \
	SDL_VIDEODRIVER=wayland \
	ELM_DISPLAY=wl \
	_JAVA_AWT_WM_NONREPARENTING=1

s6-user-session
