vim9script
set number relativenumber
set splitbelow splitright
set incsearch
set nocompatible
set updatetime=300
syntax on
filetype plugin indent on
set path+=**
set wildmenu
set wildmode=longest:full,full
set bg=dark
colo industry

g:mapleader = "\<Space>"
g:netrw_liststyle = 3
g:vimhome = substitute(expand('<sfile>:p:h'), '\', '/', 'g')

packadd vim-jetpack
jetpack#begin(g:vimhome)
Jetpack 'tani/vim-jetpack', {'opt': 1} # bootstrap
Jetpack 'Eliot00/auto-pairs'
Jetpack 'ubaldot/vim-highlight-yanked'
Jetpack 'ubaldot/vim-extended-view'
Jetpack 'prabirshrestha/vim-lsp' # LSP
Jetpack 'mattn/vim-lsp-settings'
Jetpack 'prabirshrestha/asyncomplete.vim' # auto complete
Jetpack 'prabirshrestha/asyncomplete-lsp.vim'
Jetpack 'habamax/vim-shout' # run shell commands
Jetpack 'Donaldttt/fuzzyy' # fuzzy finder
Jetpack 'tpope/vim-commentary' # comment with gc
Jetpack 'tpope/vim-fugitive', { 'on': 'G' } # git
Jetpack 'airblade/vim-gitgutter'
Jetpack 'wakatime/vim-wakatime'
Jetpack 'dstein64/vim-startuptime'
jetpack#end()

command! MakeTags !/bin/ctags -R .
command! -nargs=1 Rg Sh! rg -nS --column "<args>" .

nnoremap <Tab> :bnext<CR>
nnoremap <S-Tab> :bprevious<CR>

augroup lsp_config
	autocmd!
	autocmd User lsp_buffer_enabled call OnLspBufferEnabled()
augroup END

def OnLspBufferEnabled()
	nmap <buffer> gd <Plug>(lsp-definition)
	nmap <buffer> gr <Plug>(lsp-references)
	nmap <buffer> gi <Plug>(lsp-implementation)
	nmap <buffer> K <Plug>(lsp-hover)
	nmap <buffer> <leader>ca <Plug>(lsp-code-action)
	nmap <buffer> <leader>rn <Plug>(lsp-rename)
	nmap <buffer> [d <Plug>(lsp-previous-diagnostic)
	nmap <buffer> ]d <Plug>(lsp-next-diagnostic)
	g:lsp_format_sync_timeout = 1000
	autocmd! BufWritePre *.rs,*.go call execute('LspDocumentFormatSync')
enddef
