vim9script
set number relativenumber
set splitbelow splitright
set incsearch
set nocompatible
syntax on
filetype plugin indent on
set path+=**
set wildmenu
set bg=dark
colo retrobox
g:mapleader = " "
g:netrw_liststyle = 3
g:vimhome = substitute(expand('<sfile>:p:h'), '\', '/', 'g')

packadd vim-jetpack
jetpack#begin(g:vimhome)
Jetpack 'tani/vim-jetpack', {'opt': 1} # bootstrap
Jetpack 'Eliot00/auto-pairs'
Jetpack 'ubaldot/vim-highlight-yanked'
Jetpack 'habamax/vim-shout' # run shell commands
Jetpack 'ubaldot/vim-extended-view'
Jetpack 'yegappan/lsp'
Jetpack 'girishji/vimcomplete'
Jetpack 'Donaldttt/fuzzyy' # fuzzy finder
Jetpack 'tpope/vim-commentary' # gc for comments
Jetpack 'tpope/vim-fugitive' # :G for git commands
Jetpack 'airblade/vim-gitgutter' # git diff markers
Jetpack 'dstein64/vim-startuptime'
jetpack#end()

command! MakeTags !ctags -R .
command! -nargs=1 Rg Sh! rg -nS --column "<args>" .

nnoremap <Tab> :bnext<CR>
nnoremap <S-Tab> :bprevious<CR>

runtime lsp-setup.vim
